apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    name: mongo
    type: db
spec:
  template:
    metadata:
      name: mongo
      labels:
        name: mongo
        type: db
    spec:
      containers:
        - name: mongo-cont
          image: mongo
          ports:
            - containerPort: 27017
  # replicas: 2
  selector:
    matchLabels:
      type: db