apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    name: backend
    type: backend
spec:
  type: NodePort
  selector:
    type: backend
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30005