apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    name: frontend
    type: frontend
spec:
  type: NodePort
  selector:
    type: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004